services:
  mcp-hub:
    environment:
      - NODE_OPTIONS=--max-old-space-size=3072
      # Fix n8n connectivity - use the actual container name on shared network
      - N8N_HOST=n8n-working-n8n-1
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASE_URL=http://n8n-working-n8n-1:5678
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '0.5'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Connect to n8n network for direct container communication
    networks:
      - mcp-network
      - n8n-working_default

networks:
  n8n-working_default:
    external: true
