#!/bin/bash
# PostgreSQL setup script for MCP Hub authentication
# This script helps set up a PostgreSQL database for the authentication system

set -e

# Configuration
DB_NAME="${MCP_DB_NAME:-mcp_hub}"
DB_USER="${MCP_DB_USER:-mcp_hub_user}"
DB_PASSWORD="${MCP_DB_PASSWORD:-$(openssl rand -base64 32 | tr -d '=+/' | cut -c1-25)}"
DB_HOST="${MCP_DB_HOST:-localhost}"
DB_PORT="${MCP_DB_PORT:-5432}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if PostgreSQL is installed and running
check_postgres() {
    log_info "Checking PostgreSQL installation..."
    
    if ! command -v psql >/dev/null 2>&1; then
        log_error "PostgreSQL client (psql) not found"
        echo
        echo "To install PostgreSQL on Ubuntu/Debian:"
        echo "  sudo apt update && sudo apt install postgresql postgresql-contrib"
        echo
        echo "To install PostgreSQL on macOS:"
        echo "  brew install postgresql"
        echo "  brew services start postgresql"
        echo
        echo "To install PostgreSQL on Windows:"
        echo "  Download from: https://www.postgresql.org/download/windows/"
        exit 1
    fi
    
    log_success "PostgreSQL client found"
    
    # Check if PostgreSQL server is running
    if ! pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
        log_error "PostgreSQL server is not running or not accessible at $DB_HOST:$DB_PORT"
        echo
        echo "To start PostgreSQL:"
        echo "  Ubuntu/Debian: sudo systemctl start postgresql"
        echo "  macOS: brew services start postgresql"
        echo "  Windows: Start from Services or pgAdmin"
        exit 1
    fi
    
    log_success "PostgreSQL server is running"
}

# Create database and user
create_database() {
    log_info "Creating database and user..."
    
    # Check if database already exists
    if psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
        log_warning "Database '$DB_NAME' already exists"
    else
        log_info "Creating database '$DB_NAME'..."
        createdb -h "$DB_HOST" -p "$DB_PORT" -U postgres "$DB_NAME"
        log_success "Database '$DB_NAME' created"
    fi
    
    # Check if user already exists
    if psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
        log_warning "User '$DB_USER' already exists"
    else
        log_info "Creating user '$DB_USER'..."
        psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
        log_success "User '$DB_USER' created"
    fi
    
    # Grant privileges
    log_info "Granting privileges..."
    psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
    psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d "$DB_NAME" -c "GRANT ALL ON SCHEMA public TO $DB_USER;"
    psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d "$DB_NAME" -c "GRANT CREATE ON SCHEMA public TO $DB_USER;"
    log_success "Privileges granted"
}

# Test connection
test_connection() {
    log_info "Testing database connection..."
    
    local connection_string="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
    
    if psql "$connection_string" -c "SELECT 1;" >/dev/null 2>&1; then
        log_success "Database connection successful"
    else
        log_error "Database connection failed"
        exit 1
    fi
}

# Generate environment configuration
generate_env_config() {
    log_info "Generating environment configuration..."
    
    local connection_string="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
    
    cat > .env.database << EOF
# Database configuration generated by setup-postgres.sh
# Add these variables to your .env file

DATABASE_URL=$connection_string

# Database connection details
MCP_DB_NAME=$DB_NAME
MCP_DB_USER=$DB_USER
MCP_DB_PASSWORD=$DB_PASSWORD
MCP_DB_HOST=$DB_HOST
MCP_DB_PORT=$DB_PORT
EOF
    
    log_success "Environment configuration saved to .env.database"
    echo
    echo "Add these variables to your .env file:"
    echo "========================================="
    cat .env.database
    echo "========================================="
}

# Generate strong JWT secrets
generate_jwt_secrets() {
    log_info "Generating JWT secrets..."
    
    local jwt_secret=$(openssl rand -base64 64 | tr -d '\n')
    local jwt_refresh_secret=$(openssl rand -base64 64 | tr -d '\n')
    
    cat >> .env.database << EOF

# JWT secrets (keep these secure!)
JWT_SECRET=$jwt_secret
JWT_REFRESH_SECRET=$jwt_refresh_secret
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
EOF
    
    log_success "JWT secrets generated and added to .env.database"
}

# Main setup function
main() {
    echo
    log_info "🐘 PostgreSQL Setup for MCP Hub Authentication"
    echo "=============================================="
    echo
    
    echo "Configuration:"
    echo "- Database: $DB_NAME"
    echo "- User: $DB_USER" 
    echo "- Host: $DB_HOST:$DB_PORT"
    echo "- Password: $(echo "$DB_PASSWORD" | sed 's/./*/g')"
    echo
    
    check_postgres
    echo
    
    create_database
    echo
    
    test_connection
    echo
    
    generate_jwt_secrets
    echo
    
    generate_env_config
    echo
    
    log_success "🎉 PostgreSQL setup completed successfully!"
    echo
    echo "Next steps:"
    echo "1. Copy the environment variables from .env.database to your .env file"
    echo "2. Start MCP Hub with authentication enabled"
    echo "3. The database schema will be created automatically on first run"
    echo
    echo "To test the setup:"
    echo "  ./scripts/test-auth.sh"
    echo
    echo "For complete setup instructions, see:"
    echo "  docs/AUTHENTICATION.md"
}

# Check if running with correct permissions
if [[ $EUID -eq 0 ]]; then
    log_warning "Running as root. This script should typically be run as a regular user."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

main "$@"
